spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/taskdb}
spring.datasource.username=${DB_USERNAME:taskuser}
spring.datasource.password=${DB_PASSWORD:taskpass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
